services:
  - type: web
    name: cudillo-backend
    env: node
    rootDir: .
    buildCommand: |
      npm install
      cd ../frontend && npm install && npm run build -- --configuration production
      cd ../backend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: PORT
        value: 10000 